### PR TITLE
Update CI julia 1.6

### PR DESCRIPTION
**Pull request by geoffroyleconte**

### CODE REVIEW

**Comment by dpo** [comment]
How about in `Project.toml`? Shouldn't we also require Julia ≥ 1.6?

**Review by dpo — COMMENTED** [review]
How about in Project.toml? Shouldn't we also require Julia ≥ 1.6?

**Comment by geoffroyleconte** [comment]
> How about in Project.toml? Shouldn't we also require Julia ≥ 1.6?

Yes you are right I updated it

**Comment by dpo** [comment]
thanks

**Pull request merged**
